server:
  port: 4300
spring:
  application:
    name: monkey-question
  # ?????
  datasource:
    username: root
    password: "@Uuwusihao1931"
    url: jdbc:mysql://localhost:3306/monkey_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis ??
  redis:
    database: 0
    password: wusihao
    host: 192.168.133.138
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    #  # rabbitmq??
    #  rabbitmq:
    #    host: 192.168.133.138 # rabbitmq ???
    #    port: 5672
    #    username: wusihao
    #    password: wusihao
    #    virtual-host: powernode # ????

  # rabbitmq ??
  rabbitmq:
    addresses: 192.168.133.138:5672,192.168.133.134:5672,192.168.133.137:5672
    username: admin
    password: wusihao
    virtual-host: monkey-question # ????


# eureka集群最终配置
# eureka集群配置
eureka:
  client:
    service-url: # 指定注册地址
      defaultZone: http://peer1:8761/eureka,http://peer2:8761/eureka,http://peer3:8761/eureka
    register-with-eureka: true # 注册至eureka-server
    fetch-registry: true # 应用是否从eureka-server中拉取其他的eureka-client信息到自己
    registry-fetch-interval-seconds: 10 # 指定拉取时间
  instance:
    hostname: localhost # 应用主机名称，最好写ip
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # eurekaId
    prefer-ip-address: true # 显示ip
    lease-renewal-interval-in-seconds: 10 # 发送心跳时间（续约时间）

ribbon:
  ReadTimeout: 3000 # 设置feign跨服务调用方法的超时时间, 默认为1秒
  ConnectTimeout: 3000 # feign跨微服务方法的连接超时时间