## redis ????
#spring.redis.password=wusihao
##????????????
#spring.redis.clusterspring.redis.cluster.nodes=192.1.max-redirects=3
#spring.redis.lettuce.pool.max-active=8
#spring.redis.lettuce.pool.max-wait=-1ms
#spring.redis.lettuce.pool.max-idle=8
#spring.redis.lettuce.pool.min-idle=0
#spring.redis.cluster.nodes=192.168.133.138:6381,192.168.133.138:6382,192.168.133.134:6383,192.168.133.134:6384,192.168.133.137:6385,192.168.133.137:6386
##????????????,?????????????????????false??
#spring.redis.lettuce.cluster.refresh.adaptive=true
##????
#spring.redis.lettuce.cluster.refresh.period=2000
# rabbit ?.queue